art_auction/art/urls.py
from django.urls import path,include
from art import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

app_name = "art"
urlpatterns = [
   path('',views.index.as_view(),name="index"),
   path('signup/',views.register_user,name="register_user"),
   path('register_seller/',views.RegisterSeller.as_view(),name="register_seller"),
   path('accounts/login/',views.user_login,name="login"),
   path('profile/',views.Profile.as_view(),name="profile"),
   path('logout/',views.logout_view,name="logout"),
   path('viewdetails/<int:pk>/',views.ArtworkDetailView.as_view(),name="product_details"),
   path('artwork-sale_details/<int:pk>/',views.ArtworkSaleDetailView.as_view(),name="artwork_sale_detail"),
   path('addorder/<int:pk>',views.OrderCreateView.as_view(),name="place_order"),
   path('sale-order/<int:pk>',views.SaleOrderCreateView.as_view(),name="sale_order"),
   path('orderconfirm/',views.OrderCreateView.as_view(),name="confirm_order"),
   path("callback/", views.callback, name="callback"),
   path("arview/<int:id>", views.ArView.as_view(), name="view_3d"),
   path('arview/update/', views.ArView.as_view(), name='arview-update'),
   # path('360view/<int:id>/', views.View360.as_view(), name='view360'),
   path("about/", views.About.as_view(), name="about"),
   path("contact/", views.Contact.as_view(), name="contact"),
   path("faq/", views.FAQs.as_view(), name="faq"),
   path("terms/", views.Terms.as_view(), name="terms"),
   path("privacy/", views.Privacy.as_view(), name="privacy"),
   path("purchase_cancel/", views.Purchase_Cancel.as_view(), name="purchase_cancel"),
   path("auction_cancel/", views.Auction_Cancel.as_view(), name="auction_cancel"),
   path('unsold/',views.UnsoldListView.as_view(),name="unsold_items"),
   path('artwork-sale/',views.ArtworkSaleListView.as_view(),name="artwork_sale"),
   path('cat/<int:id>/',views.CatListView.catalog_products,name="catalog_products"),
   path('purchase-cat/<int:id>/', views.PurchaseCategoryView.as_view(), name="purchase_category_products"),
   path('profile-settings/', views.profile_settings, name='profile_settings'),
   path('toggle_favorite/', views.toggle_favorite, name='toggle_favorite'),   
   path('favorites/', views.favorites_page, name='favorites_page'),
   path('get_favorites/', views.get_favorites, name='get_favorites'),
   path('remove-favorite/<int:artwork_id>/', views.remove_favorite, name='remove_favorite'),
]
if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

art_auction/art_auction/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("art.urls", namespace="art")),
    path("dashboard/", include("dashboard.urls", namespace="dashboard")),
    path("registration/", include("registration.urls")),
]

art_auction/dashboard/urls.py
from django.urls import path
from dashboard import views
from django.conf import settings  # Correct import
from django.conf.urls.static import static

app_name = "dashboard"
urlpatterns = [
    path('addproduct/', views.ArtworkCreateView.as_view(), name="add_product"),
    path('product/', views.ArtworkListView.as_view(), name="product_list"),
    path('bidlist/', views.BidListView.as_view(), name="bid_list"),
    path('productupdate/<int:pk>/', views.ArtworkUpdateView.as_view(), name="product_update"),
    path('product/<int:pk>/delete/', views.ArtworkDeleteView.as_view(), name="product_delete"),
    path('order/', views.OrderListView.as_view(), name="order_list"),
    path('placebid/', views.BidCreateView.as_view(), name="place_bid"),
    path('latest_bid/<int:pk>/', views.latest_bid, name='latest_bid'),
    path('fetch_notifications/', views.fetch_notifications, name='fetch_notifications'),
    path('notifications/mark_as_read/<int:notification_id>/', views.mark_notification_as_read, name='mark_notification_as_read'),
    path('dismiss_notification/<int:notification_id>/', views.dismiss_notification, name='dismiss_notification'),
    path('clear_all_notifications/', views.clear_all_notifications, name='clear_all_notifications'),
    path('submit_query/', views.SubmitQueryView.as_view(), name='submit_query'),
    path('submit-feedback/', views.submit_feedback, name='submit_feedback'),
    path('contact/', views.SubmitQueryView.as_view(), name='contact'),
    # path('check_auction_status/', views.check_auction_status, name='check_auction_status'),
    path('confirm_purchase/<int:artwork_id>/', views.confirm_purchase, name='confirm_purchase'),
    path('get_shipping_status/<int:order_id>/', views.get_shipping_status, name='get_shipping_status'),
    path('update_shipping_status/', views.update_shipping_status, name='update_shipping_status'),
    path('cancel_order/', views.cancel_order, name='cancel_order'),
    path('autocomplete/', views.autocomplete_artworks, name='autocomplete_artworks'),
    path('get_artworks_json/', views.get_artworks_json, name='get_artworks_json'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

art_auction/registration/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = 'registration'

urlpatterns = [
    path('password_reset/', views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'), name='password_reset_complete'),
]

art_auction/art/models.py
# models.py
from django.db import models
from django.conf import settings

class SellerInfo(models.Model):
    phone_number = models.CharField(max_length=17, blank=False, default='', help_text="Please enter the phone number, without +91")
    business_name = models.CharField(max_length=255, null=True, blank=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='sellerinfo')

    def __str__(self):
        return f'user : {self.user}'

class UserInfo(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='userinfo')
    first_name = models.CharField(max_length=150, blank=True, null=True)
    last_name = models.CharField(max_length=150, blank=True, null=True)
    email = models.EmailField(max_length=254, blank=True, null=True)
    phone_number = models.CharField(max_length=17, blank=False, default='', help_text="Please enter the phone number, without +91")
    
    def __str__(self):
        return f"User Info: {self.user}"

art_auction/dashboard/models.py
from datetime import datetime, time
from time import localtime
import uuid
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from PIL import Image
import imagehash
from django.core.exceptions import ValidationError
from django.utils.timezone import now
from django.utils.timezone import make_aware
import pytz
from django.urls import reverse

class Catalogue(models.Model):
    cat_name = models.CharField(max_length=255)

    def __str__(self):
        return self.cat_name

class PurchaseCategory(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name
class Artwork(models.Model):
    SALE_TYPE_CHOICES = [
        ("discount", "Discount"),
        ("auction", "Auction"),
    ]

    sale_type = models.CharField(
        max_length=50, choices=SALE_TYPE_CHOICES, default="auction"
    )
    product_id = models.CharField(max_length=255, default="", null=True)
    product_name = models.CharField(max_length=255, null=True)
    product_price = models.IntegerField(default=0, null=True)
    model_360 = models.FileField(upload_to="3d_models/", null=True, blank=True)  # 360 View Field
    opening_bid = models.IntegerField(default=0, null=True, blank=True)
    product_cat = models.ForeignKey(
        Catalogue, on_delete=models.CASCADE, null=True, blank=True
    )
    purchase_category = models.ForeignKey(  # Add this field
        PurchaseCategory, on_delete=models.CASCADE, null=True, blank=True
    )
    product_qty = models.IntegerField(default=0, null=True)
    product_image = models.ImageField(upload_to="arts/")
    dimension_unit = models.CharField(
        max_length=10, choices=[("cm", "Centimeters"), ("ft", "Feet")]
    )
    length_in_centimeters = models.FloatField(default=0, blank=True, null=True)
    width_in_centimeters = models.FloatField(default=0, blank=True, null=True)
    foot = models.FloatField(default=0, blank=True, null=True)
    inches = models.FloatField(default=0, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    end_date = models.DateField(null=True, blank=True, db_index=True)
    favorited_by = models.ManyToManyField(User, related_name="favorite_artworks", blank=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True
    )
    is_sold = models.BooleanField(default=False)
    is_purchased = models.BooleanField(default=False)
    status = models.CharField(
        max_length=50,
        choices=[
            ("active", "Active"),
            ("closed", "Closed"),
            ("waiting_for_response", "Waiting for Response"),
            ("unsold", "Unsold"),
        ],
        default="active",
    )
    response_deadline = models.DateTimeField(blank=True, null=True, db_index=True)
    buyer_response = models.CharField(
        max_length=11,
        choices=[("yes", "Yes"), ("no", "No"), ("no_response", "No Response")],
        default="no_response",
    )
    discounted_price = models.DecimalField(
        max_digits=10, decimal_places=2, null=True, blank=True
    )
    def save(self, *args, **kwargs):
        """ Automatically assign categories based on sale_type and generate a product_id. """
        if not self.product_id:  # Only generate product_id if it doesn't already exist
            self.product_id = str(uuid.uuid4())  # Generate a unique product_id using UUID

        if self.sale_type == 'discount':
            self.product_cat = None  # Ensure product_cat is empty
        elif self.sale_type == 'auction':
            self.purchase_category = None  # Ensure purchase_category is empty
        
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('art:catalog_products', kwargs={'pk': self.product_cat.id})
    
    def get_discounted_price(self):
        """Calculate 30% discounted price."""
        return self.product_price * 0.7

    def clean(self):
        """Validation for discount and auction artworks."""
        super().clean()

        if self.sale_type == "discount":
            self.opening_bid = None
            self.end_date = None
            if self.discounted_price is None:
                self.discounted_price = self.get_discounted_price()
            elif self.discounted_price >= self.product_price:
                raise ValidationError(
                    {
                        "discounted_price": "Discounted price must be less than the product price."
                    }
                )

        elif self.sale_type == "auction":
            if not self.product_cat:
                raise ValidationError(
                    {"product_cat": "Product category is required for bidding."}
                )
            if not self.opening_bid:
                raise ValidationError(
                    {"opening_bid": "Opening bid is required for bidding."}
                )
            if not self.end_date:
                raise ValidationError({"end_date": "End date is required for bidding."})

    def save(self, *args, **kwargs):
        """Ensure correct fields are set before saving, and check for duplicate images."""
        self.full_clean()  # Explicitly validate before saving
        
        if self.sale_type == "discount":
            self.opening_bid = None
            self.end_date = None
            self.product_cat = None  # Ensure product_cat is empty
    
            if self.discounted_price is None:
                self.discounted_price = self.get_discounted_price()
    
        elif self.sale_type == "auction":
            self.purchase_category = None  # Ensure purchase_category is empty
            if not self.opening_bid or not self.end_date:
                raise ValidationError("Opening bid and End date are required for auction.")
    
        if self.product_image:
            uploaded_image_hash = imagehash.phash(Image.open(self.product_image))
            existing_images = Artwork.objects.exclude(id=self.id)
    
            for artwork in existing_images:
                stored_image_hash = imagehash.phash(Image.open(artwork.product_image.path))
                if uploaded_image_hash == stored_image_hash:
                    raise ValidationError("Duplicate image detected. This artwork is already uploaded.")
    
        if self.end_date:
            self.end_date = timezone.make_aware(datetime.combine(self.end_date, time.min))
    
        super().save(*args, **kwargs)


    def __str__(self):
        return self.product_name

    def get_last_bid(self):
        last_bid = self.bids.order_by("-bid_amt").first()
        return last_bid.bid_amt if last_bid else self.opening_bid

    def get_total_bids(self):
        return self.bids.count()

    def mark_as_sold(self):
        self.is_sold = True
        self.save()


class OrderModel(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Artwork, on_delete=models.CASCADE)
    order_date = models.DateField(auto_now_add=True)
    order_qty = models.IntegerField(default=0, null=False)
    delivery_at = models.TextField(default=" ", null=False)
    order_price = models.FloatField(default=0, null=False)

    def __str__(self):
        return f"order of {self.product} by {self.user}"


class Bid(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Artwork, on_delete=models.CASCADE, related_name="bids")
    bid_date = models.DateField(auto_now_add=True)
    bid_amt = models.IntegerField(default=1)

    def __str__(self):
        return f"bid of {self.product} on {self.bid_date}"


class Payment(models.Model):
    order = models.ForeignKey(OrderModel, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    status = models.CharField(
        _("Payment Status"), max_length=254, default="Pending", blank=False, null=False
    )
    provider_order_id = models.CharField(
        _("Order ID"), max_length=40, null=False, blank=False
    )
    payment_id = models.CharField(
        _("Payment ID"), max_length=36, null=False, blank=False
    )
    signature_id = models.CharField(
        _("Signature ID"), max_length=128, null=False, blank=False
    )
    payment_method = models.CharField(max_length=50, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Payment {self.provider_order_id}"


class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(
        Artwork, on_delete=models.CASCADE, null=True, blank=True
    )  # Adjust as necessary
    message = models.TextField()
    read = models.BooleanField(default=False)
    read_at = models.DateTimeField(null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)


class Query(models.Model):
    full_name = models.CharField(max_length=100)
    email = models.EmailField()
    query = models.TextField()
    category = models.CharField(max_length=50)
    submitted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.full_name} - {self.category}"


from django.db import models


class Feedback(models.Model):
    RATING_CHOICES = [
        ("Poor", "Poor"),
        ("Fair", "Fair"),
        ("Good", "Good"),
        ("Very Good", "Very Good"),
        ("Excellent", "Excellent"),
    ]

    rating = models.CharField(
        max_length=10, choices=RATING_CHOICES, null=True, blank=True
    )
    feedback_text = models.TextField(blank=True, null=True)
    sentiment = models.CharField(
        max_length=10,
        choices=[
            ("positive", "Positive"),
            ("negative", "Negative"),
            ("neutral", "Neutral"),
        ],
        blank=True,
        null=True,

art_auction/templates/art/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    
    <!-- Favicon -->
    <link rel="icon" href="{% static 'images/assets/ARTIV ICON.png' %}" type="image/x-icon">

    <!-- CSS Files -->
    <link rel="stylesheet" href="{% static 'dashboard/css/style.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'dashboard/css/contact.css' %}" type="text/css">
    {% block css_file %}{% endblock %}

    <!-- Bootstrap CSS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />

    <!-- Page Title -->
    <title>{% block title %}{% endblock %}</title>
    
    <!-- Meta Tags -->
    <meta name="title" content="{% block meta_title %}{% endblock %}">
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="keywords" content="{% block keywords %}{% endblock %}">
    <meta name="robots" content="{% block robot %}{% endblock %}">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="language" content="English">
    <meta name="revisit-after" content="3 days">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
    <div class="loader"></div>
    {% block header %}
    <!-- Add your header content here -->
    {% endblock %}

    {% block body %}
    <!-- Main content will be injected here by child templates -->
    {% endblock %}
    
    <footer>
        {% block footer %}
        <div class="footer-container poppins-regular-footer">
            <div class="footer-content poppins-regular-footer">
                <ul class="footer-links">
                    <li><a href="{% url 'art:about' %}">About Us</a></li>
                    <li><a href="{% url 'art:contact' %}">Contact Us</a></li>
                    <li><a href="{% url 'art:faq' %}">FAQs</a></li>
                    <li><a href="{% url 'art:terms' %}">Terms of Use</a></li>
                    <li><a href="{% url 'art:privacy' %}">Privacy Policy</a></li>
    
                    {% if request.resolver_match.url_name in "purchase_category_products,artwork_sale" %}
                        <!-- Show only Purchase Cancellation Policy -->
                        <li><a href="{% url 'art:purchase_cancel' %}">Purchase Cancellation Policy</a></li>
    
                    {% elif request.resolver_match.url_name in "index,product_details,place_order,confirm_order,callback,unsold_items,catalog_products" %}
                        <!-- Show only Auction Cancellation Policy -->
                        <li><a href="{% url 'art:auction_cancel' %}">Auction Cancellation Policy</a></li>
    
                    {% else %}
                        <!-- Show both policies -->
                        <li><a href="{% url 'art:purchase_cancel' %}">Purchase Cancellation Policy</a></li>
                        <li><a href="{% url 'art:auction_cancel' %}">Auction Cancellation Policy</a></li>
                    {% endif %}
                </ul>
                <p>&copy; 2025 ARTIV. All rights reserved.</p>
            </div>
        </div>
        {% endblock %}
    </footer>    
    {% block js %}{% endblock %}

    <script>
        $(document).ready(function() {
            $('.loader').fadeOut();
        });
    </script>

    {% comment %} <script src="https://kit.fontawesome.com/d400ed2add.js" crossorigin="anonymous"></script> {% endcomment %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/js/all.min.js" integrity="sha512-rpLlll167T5LJHwp0waJCh3ZRf7pO6IT1+LZOhAyP6phAirwchClbTZV3iqL3BMrVxIYRbzGTpli4rfxsCK6Vw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
</body>
</html>

art_auction/templates/art/order_form.html
{% extends './layout.html' %}
{% load static %}
{% block title %}Checkout - ARTIV{% endblock %}
{% block robot %}index, follow{% endblock %}
{% block css_file %}
<link rel="stylesheet" href="{% static 'dashboard/css/form.css' %}" type="text/css">
<script>
    (function() {
    const theme = localStorage.getItem('theme') || 'auto';
    const prefersDarkScheme = window.matchMedia("(prefers-color-scheme: dark)").matches;
    const isDarkMode = theme === 'dark' || (theme === 'auto' && prefersDarkScheme);
    
    if (isDarkMode) {
        document.body.classList.add('dark-mode');
    } else {
        document.body.classList.add('light-mode');
    }
    })();
</script>
<style>
    .button-container {
        position: absolute;
        top: 85px; /* Adjust the value to move vertically */
        left: 2rem; /* Adjust the value to move horizontally */
    }
</style>
{% endblock %}
{% block body %}
{% load i18n %}
{% load static %}

{% include "./includes/navbar.html" %}
<br>
{% include "./arrow_button.html" %}
<div class="button-container">
    <i class="fa-solid fa-arrow-left" style="cursor:pointer; font-size:1.4rem; margin-right:10px" onclick="goBack()"></i>
    <i class="fa-solid fa-arrow-right" style="cursor:pointer; font-size:1.4rem; margin-right:15px" onclick="goForward()"></i>
</div>
<div class="container p-4 poppins-regular-order">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-4">
                    <h5>{{ product.product_name }}</h5>
                    <img src="{{ MEDIA_URL }}{{ product.product_image }}" alt="img" width="100%" />
                    <br>
                    <br>
                    <table class="table table-bordered">
                        <tbody>
                            <tr>
                                <th>Catalogue</th>
                                <td>{{ product.product_cat }}</td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="d-grid gap-2">
                        <a class="btn btn-primary_details" type="button" href="{% url 'art:view_3d' id=product.id %}">View in AR</a>
                    </div>
                </div>
                <div class="col-8">
                    <div class="app-card shadow-sm h-100">
                        <div class="app-card-body p-2">
                            <form method="POST" enctype="multipart/form-data" action="{% url 'art:confirm_order' %}">
                                {% csrf_token %}
                                <input type="hidden" name="product" value="{{ product.pk }}">  {# Add this line to include the product ID #}
                                <div class="fieldWrapper">
                                    <label for="id_product_price">Latest Artwork price:</label>
                                    <input type="number" name="product_price" value="{{ last_bid.bid_amt }}" required="" id="id_product_price" readonly>
                                </div>
                                <div class="fieldWrapper">
                                    <label for="id_product_qty">Artwork Quantity:</label>
                                    <input type="number" name="product_qty" value="1" min="1" max="{{ product.product_qty }}" required="" id="id_product_qty" onchange="getTotal()" readonly>
                                </div>
                                <div class="fieldWrapper">
                                    <label for="id_product_qty">Delivery Address:</label>
                                    <textarea name="delivery_at" required></textarea>
                                </div>
                                <div class="fieldWrapper">
                                    <label for="id_product_qty">Total:</label>
                                    <h5 id="id_product_total"></h5>
                                </div>
                                <div class="d-grid mx-auto">
                                    <input class="btn btn-warning_buy" type="submit" value="Proceed to pay">
                                </div>
                            </form>
                        </div>
                    </div>
                    <!--//app-card-->
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'js/theme.js' %}"></script>
<script>
    function getTotal() {
        const price = document.getElementById('id_product_price').value;
        const qty = document.getElementById('id_product_qty').value;
        document.getElementById('id_product_total').innerText = price * qty;
    }

    getTotal();
</script>

{% endblock %}

art_auction/templates/art/sale-order-form.html
{% extends './layout.html' %}
{% load static %}
{% block title %}Checkout - ARTIV{% endblock %}
{% block robot %}index, follow{% endblock %}
{% block css_file %}
<link rel="stylesheet" href="{% static 'dashboard/css/form.css' %}" type="text/css">
<script>
    (function() {
    const theme = localStorage.getItem('theme') || 'auto';
    const prefersDarkScheme = window.matchMedia("(prefers-color-scheme: dark)").matches;
    const isDarkMode = theme === 'dark' || (theme === 'auto' && prefersDarkScheme);
    
    if (isDarkMode) {
        document.body.classList.add('dark-mode');
    } else {
        document.body.classList.add('light-mode');
    }
    })();
</script>
<style>
    .button-container {
        position: absolute;
        top: 85px; /* Adjust the value to move vertically */
        left: 2rem; /* Adjust the value to move horizontally */
    }
</style>
{% endblock %}
{% block body %}
{% load i18n %}
{% load static %}

{% include "./includes/navbar.html" %}
<br>
{% include "./arrow_button.html" %}
<div class="button-container">
    <i class="fa-solid fa-arrow-left" style="cursor:pointer; font-size:1.4rem; margin-right:10px" onclick="goBack()"></i>
    <i class="fa-solid fa-arrow-right" style="cursor:pointer; font-size:1.4rem; margin-right:15px" onclick="goForward()"></i>
</div>
<div class="container p-4 poppins-regular-order">
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-4">
                    <h5>{{ product.product_name }}</h5>
                    <img src="{{ MEDIA_URL }}{{ product.product_image }}" alt="img" width="100%" />
                    <br>
                    <br>
                    <table class="table table-bordered">
                        <tbody>
                            <tr>
                                <th>Catalogue</th>
                                <td>{{ product.product_cat }}</td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="d-grid gap-2">
                        <a class="btn btn-primary" type="button" href="{% url 'art:view_3d' id=product.id %}">View in AR</a>
                    </div>
                </div>
                <div class="col-8">
                    <div class="app-card shadow-sm h-100">
                        <div class="app-card-body p-2">
                            <form method="POST" enctype="multipart/form-data" action="{% url 'art:confirm_order' %}">
                                {% csrf_token %}
                                <input type="hidden" name="product" value="{{ product.pk }}">  {# Add this line to include the product ID #}
                                <div class="fieldWrapper">
                                    <label for="id_product_price">
                                        {% if is_first_purchase %}
                                            Discounted Price (30% off):
                                        {% else %}
                                            Original Price:
                                        {% endif %}
                                    </label>
                                    <input type="number" name="product_price" value="{{ price|floatformat:0 }}" required="" id="id_product_price" readonly>
                                </div>
                                <div class="fieldWrapper">
                                    <label for="id_product_qty">Artwork Quantity:</label>
                                    <input type="number" name="product_qty" value="1" min="1" max="{{ product.product_qty }}" required="" id="id_product_qty" onchange="getTotal()" readonly>
                                </div>
                                <div class="fieldWrapper">
                                    <label for="id_product_qty">Delivery Address:</label>
                                    <textarea name="delivery_at" required></textarea>
                                </div>
                                <div class="fieldWrapper">
                                    <label for="id_product_qty">Total:</label>
                                    <h5 id="id_product_total"></h5>
                                </div>
                                <div class="d-grid mx-auto">
                                    <input class="btn btn-success" type="submit" value="Proceed to pay">
                                </div>
                            </form>
                        </div>
                    </div>
                    <!--//app-card-->
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'js/theme.js' %}"></script>
<script>
    function getTotal() {
        const price = document.getElementById('id_product_price').value;
        const qty = document.getElementById('id_product_qty').value;
        document.getElementById('id_product_total').innerText = price * qty;
    }

    getTotal();
</script>

{% endblock %}