art_auction/art/urls.py
from django.urls import path,include
from art import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

app_name = "art"
urlpatterns = [
   path('',views.index.as_view(),name="index"),
   path('signup/',views.register_user,name="register_user"),
   path('register_seller/',views.RegisterSeller.as_view(),name="register_seller"),
   path('accounts/login/',views.user_login,name="login"),
   path('profile/',views.Profile.as_view(),name="profile"),
   path('logout/',views.logout_view,name="logout"),
   path('viewdetails/<int:pk>/',views.ArtworkDetailView.as_view(),name="product_details"),
   path('artwork-sale_details/<int:pk>/',views.ArtworkSaleDetailView.as_view(),name="artwork_sale_detail"),
   path('addorder/<int:pk>',views.OrderCreateView.as_view(),name="place_order"),
   path('sale-order/<int:pk>',views.SaleOrderCreateView.as_view(),name="sale_order"),
   path('orderconfirm/',views.OrderCreateView.as_view(),name="confirm_order"),
   path("callback/", views.callback, name="callback"),
   path("arview/<int:id>", views.ArView.as_view(), name="view_3d"),
   path('arview/update/', views.ArView.as_view(), name='arview-update'),
   # path('360view/<int:id>/', views.View360.as_view(), name='view360'),
   path("about/", views.About.as_view(), name="about"),
   path("contact/", views.Contact.as_view(), name="contact"),
   path("faq/", views.FAQs.as_view(), name="faq"),
   path("terms/", views.Terms.as_view(), name="terms"),
   path("privacy/", views.Privacy.as_view(), name="privacy"),
   path("purchase_cancel/", views.Purchase_Cancel.as_view(), name="purchase_cancel"),
   path("auction_cancel/", views.Auction_Cancel.as_view(), name="auction_cancel"),
   path('unsold/',views.UnsoldListView.as_view(),name="unsold_items"),
   path('artwork-sale/',views.ArtworkSaleListView.as_view(),name="artwork_sale"),
   path('cat/<int:id>/',views.CatListView.catalog_products,name="catalog_products"),
   path('purchase-cat/<int:id>/', views.PurchaseCategoryView.as_view(), name="purchase_category_products"),
   path('profile-settings/', views.profile_settings, name='profile_settings'),
   path('toggle_favorite/', views.toggle_favorite, name='toggle_favorite'),   
   path('favorites/', views.favorites_page, name='favorites_page'),
   path('get_favorites/', views.get_favorites, name='get_favorites'),
   path('remove-favorite/<int:artwork_id>/', views.remove_favorite, name='remove_favorite'),
]
if settings.DEBUG:
   urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

art_auction/art_auction/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("art.urls", namespace="art")),
    path("dashboard/", include("dashboard.urls", namespace="dashboard")),
    path("registration/", include("registration.urls")),
]

art_auction/dashboard/urls.py
from django.urls import path
from dashboard import views
from django.conf import settings  # Correct import
from django.conf.urls.static import static

app_name = "dashboard"
urlpatterns = [
    path('addproduct/', views.ArtworkCreateView.as_view(), name="add_product"),
    path('product/', views.ArtworkListView.as_view(), name="product_list"),
    path('bidlist/', views.BidListView.as_view(), name="bid_list"),
    path('productupdate/<int:pk>/', views.ArtworkUpdateView.as_view(), name="product_update"),
    path('product/<int:pk>/delete/', views.ArtworkDeleteView.as_view(), name="product_delete"),
    path('order/', views.OrderListView.as_view(), name="order_list"),
    path('placebid/', views.BidCreateView.as_view(), name="place_bid"),
    path('latest_bid/<int:pk>/', views.latest_bid, name='latest_bid'),
    path('fetch_notifications/', views.fetch_notifications, name='fetch_notifications'),
    path('notifications/mark_as_read/<int:notification_id>/', views.mark_notification_as_read, name='mark_notification_as_read'),
    path('dismiss_notification/<int:notification_id>/', views.dismiss_notification, name='dismiss_notification'),
    path('clear_all_notifications/', views.clear_all_notifications, name='clear_all_notifications'),
    path('submit_query/', views.SubmitQueryView.as_view(), name='submit_query'),
    path('submit-feedback/', views.submit_feedback, name='submit_feedback'),
    path('contact/', views.SubmitQueryView.as_view(), name='contact'),
    # path('check_auction_status/', views.check_auction_status, name='check_auction_status'),
    path('confirm_purchase/<int:artwork_id>/', views.confirm_purchase, name='confirm_purchase'),
    path('get_shipping_status/<int:order_id>/', views.get_shipping_status, name='get_shipping_status'),
    path('update_shipping_status/', views.update_shipping_status, name='update_shipping_status'),
    path('cancel_order/', views.cancel_order, name='cancel_order'),
    path('autocomplete/', views.autocomplete_artworks, name='autocomplete_artworks'),
    path('get_artworks_json/', views.get_artworks_json, name='get_artworks_json'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

art_auction/dashboard/models.py
from datetime import datetime, time
from time import localtime
import uuid
from django.db import models
from django.utils import timezone
from django.conf import settings
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from PIL import Image
import imagehash
from django.core.exceptions import ValidationError
from django.utils.timezone import now
from django.utils.timezone import make_aware
import pytz
from django.urls import reverse

class Catalogue(models.Model):
    cat_name = models.CharField(max_length=255)

    def __str__(self):
        return self.cat_name

class PurchaseCategory(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name
class Artwork(models.Model):
    SALE_TYPE_CHOICES = [
        ("discount", "Discount"),
        ("auction", "Auction"),
    ]

    sale_type = models.CharField(
        max_length=50, choices=SALE_TYPE_CHOICES, default="auction"
    )
    product_id = models.CharField(max_length=255, default="", null=True)
    product_name = models.CharField(max_length=255, null=True)
    product_price = models.IntegerField(default=0, null=True)
    model_360 = models.FileField(upload_to="3d_models/", null=True, blank=True)  # 360 View Field
    opening_bid = models.IntegerField(default=0, null=True, blank=True)
    product_cat = models.ForeignKey(
        Catalogue, on_delete=models.CASCADE, null=True, blank=True
    )
    purchase_category = models.ForeignKey(  # Add this field
        PurchaseCategory, on_delete=models.CASCADE, null=True, blank=True
    )
    product_qty = models.IntegerField(default=0, null=True)
    product_image = models.ImageField(upload_to="arts/")
    dimension_unit = models.CharField(
        max_length=10, choices=[("cm", "Centimeters"), ("ft", "Feet")]
    )
    length_in_centimeters = models.FloatField(default=0, blank=True, null=True)
    width_in_centimeters = models.FloatField(default=0, blank=True, null=True)
    foot = models.FloatField(default=0, blank=True, null=True)
    inches = models.FloatField(default=0, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    end_date = models.DateField(null=True, blank=True, db_index=True)
    favorited_by = models.ManyToManyField(User, related_name="favorite_artworks", blank=True)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True
    )
    is_sold = models.BooleanField(default=False)
    is_purchased = models.BooleanField(default=False)
    status = models.CharField(
        max_length=50,
        choices=[
            ("active", "Active"),
            ("closed", "Closed"),
            ("waiting_for_response", "Waiting for Response"),
            ("unsold", "Unsold"),
        ],
        default="active",
    )
    response_deadline = models.DateTimeField(blank=True, null=True, db_index=True)
    buyer_response = models.CharField(
        max_length=11,
        choices=[("yes", "Yes"), ("no", "No"), ("no_response", "No Response")],
        default="no_response",
    )
    discounted_price = models.DecimalField(
        max_digits=10, decimal_places=2, null=True, blank=True
    )
    def save(self, *args, **kwargs):
        """ Automatically assign categories based on sale_type and generate a product_id. """
        if not self.product_id:  # Only generate product_id if it doesn't already exist
            self.product_id = str(uuid.uuid4())  # Generate a unique product_id using UUID

        if self.sale_type == 'discount':
            self.product_cat = None  # Ensure product_cat is empty
        elif self.sale_type == 'auction':
            self.purchase_category = None  # Ensure purchase_category is empty
        
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('art:catalog_products', kwargs={'pk': self.product_cat.id})
    
    def get_discounted_price(self):
        """Calculate 30% discounted price."""
        return self.product_price * 0.7

    def clean(self):
        """Validation for discount and auction artworks."""
        super().clean()

        if self.sale_type == "discount":
            self.opening_bid = None
            self.end_date = None
            if self.discounted_price is None:
                self.discounted_price = self.get_discounted_price()
            elif self.discounted_price >= self.product_price:
                raise ValidationError(
                    {
                        "discounted_price": "Discounted price must be less than the product price."
                    }
                )

        elif self.sale_type == "auction":
            if not self.product_cat:
                raise ValidationError(
                    {"product_cat": "Product category is required for bidding."}
                )
            if not self.opening_bid:
                raise ValidationError(
                    {"opening_bid": "Opening bid is required for bidding."}
                )
            if not self.end_date:
                raise ValidationError({"end_date": "End date is required for bidding."})

    def save(self, *args, **kwargs):
        """Ensure correct fields are set before saving, and check for duplicate images."""
        self.full_clean()  # Explicitly validate before saving
        
        if self.sale_type == "discount":
            self.opening_bid = None
            self.end_date = None
            self.product_cat = None  # Ensure product_cat is empty
    
            if self.discounted_price is None:
                self.discounted_price = self.get_discounted_price()
    
        elif self.sale_type == "auction":
            self.purchase_category = None  # Ensure purchase_category is empty
            if not self.opening_bid or not self.end_date:
                raise ValidationError("Opening bid and End date are required for auction.")
    
        if self.product_image:
            uploaded_image_hash = imagehash.phash(Image.open(self.product_image))
            existing_images = Artwork.objects.exclude(id=self.id)
    
            for artwork in existing_images:
                stored_image_hash = imagehash.phash(Image.open(artwork.product_image.path))
                if uploaded_image_hash == stored_image_hash:
                    raise ValidationError("Duplicate image detected. This artwork is already uploaded.")
    
        if self.end_date:
            self.end_date = timezone.make_aware(datetime.combine(self.end_date, time.min))
    
        super().save(*args, **kwargs)


    def __str__(self):
        return self.product_name

    def get_last_bid(self):
        last_bid = self.bids.order_by("-bid_amt").first()
        return last_bid.bid_amt if last_bid else self.opening_bid

    def get_total_bids(self):
        return self.bids.count()

    def mark_as_sold(self):
        self.is_sold = True
        self.save()


class OrderModel(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Artwork, on_delete=models.CASCADE)
    order_date = models.DateField(auto_now_add=True)
    order_qty = models.IntegerField(default=0, null=False)
    delivery_at = models.TextField(default=" ", null=False)
    order_price = models.FloatField(default=0, null=False)

    def __str__(self):
        return f"order of {self.product} by {self.user}"


class Bid(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Artwork, on_delete=models.CASCADE, related_name="bids")
    bid_date = models.DateField(auto_now_add=True)
    bid_amt = models.IntegerField(default=1)

    def __str__(self):
        return f"bid of {self.product} on {self.bid_date}"


class Payment(models.Model):
    order = models.ForeignKey(OrderModel, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    status = models.CharField(
        _("Payment Status"), max_length=254, default="Pending", blank=False, null=False
    )
    provider_order_id = models.CharField(
        _("Order ID"), max_length=40, null=False, blank=False
    )
    payment_id = models.CharField(
        _("Payment ID"), max_length=36, null=False, blank=False
    )
    signature_id = models.CharField(
        _("Signature ID"), max_length=128, null=False, blank=False
    )
    payment_method = models.CharField(max_length=50, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Payment {self.provider_order_id}"


class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(
        Artwork, on_delete=models.CASCADE, null=True, blank=True
    )  # Adjust as necessary
    message = models.TextField()
    read = models.BooleanField(default=False)
    read_at = models.DateTimeField(null=True, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)


class Query(models.Model):
    full_name = models.CharField(max_length=100)
    email = models.EmailField()
    query = models.TextField()
    category = models.CharField(max_length=50)
    submitted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.full_name} - {self.category}"


from django.db import models


class Feedback(models.Model):
    RATING_CHOICES = [
        ("Poor", "Poor"),
        ("Fair", "Fair"),
        ("Good", "Good"),
        ("Very Good", "Very Good"),
        ("Excellent", "Excellent"),
    ]

    rating = models.CharField(
        max_length=10, choices=RATING_CHOICES, null=True, blank=True
    )
    feedback_text = models.TextField(blank=True, null=True)
    sentiment = models.CharField(
        max_length=10,
        choices=[
            ("positive", "Positive"),
            ("negative", "Negative"),
            ("neutral", "Neutral"),
        ],
        blank=True,
        null=True,

art_auction/templates/dashboard/artwork_confirm_delete.html
{% extends './base.html' %} {% block title %}Artwork Delete? - ARTIV{% endblock %} {% load static %} {% block links %}
<link rel="stylesheet" href="{% static 'dashboard/css/artwork_delete.css' %}">
{% endblock %} {% block content %}
{% include './includes/header.html' %}
{% include "art/arrow_button.html" %}



    <div class="app-content pt-3 p-md-3 p-lg-4">
        <div class="button-container">
            <i class="fa-solid fa-arrow-left" style="cursor:pointer; font-size:1.4rem; margin-right:10px" onclick="goBack()"></i>
            <i class="fa-solid fa-arrow-right" style="cursor:pointer; font-size:1.4rem; margin-right:15px" onclick="goForward()"></i>
        </div>
        <div class="container">

            <h1 class="app-page-title">Delete artworks</h1>


            <div class="row g-4 mb-4">
                <div class="col-12">
                    <div class="app-card shadow-sm h-100">
                        <div class="app-card-body app-card-delete p-2">
                            <form method="post">{% csrf_token %}
                                <p>Are you sure you want to delete "{{ object }}"?</p>
                                {{ form }}
                                <button class="btn btn-confirm_delete" style="border-radius:5px;" type="submit">
                                    Confirm
                                </button>
                            </form>
                        </div>

                    </div>
                    <!--//app-card-->
                </div>

            </div>


        </div>
        <!--//container-fluid-->
    </div>
    <!--//app-content-->


    {% include './includes/footer.html' %}

{% endblock %} {% block js %}
{% endblock %}
{% block jscript %}
(function(){scroller();}());
{% endblock %}

art_auction/templates/dashboard/artwork_list.html
{% extends './base.html' %}
{% block title %}Artworks List - ARTIV{% endblock %}
{% load static %}
{% block links %}
<link rel="stylesheet" href="{% static 'dashboard/css/artwork_list.css' %}">
<link rel="stylesheet" href="{% static 'dashboard/css/ordermodel_list.css' %}">
<link rel="stylesheet" href="{% static 'dashboard/css/index.css' %}">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
<script>
    (function () {
        const theme = localStorage.getItem("theme") || "auto";
        const prefersDarkScheme = window.matchMedia("(prefers-color-scheme: dark)").matches;
        const isDarkMode = theme === "dark" || (theme === "auto" && prefersDarkScheme);
    
    if (isDarkMode) {
        document.documentElement.classList.add("dark-mode");
    } else {
        document.documentElement.classList.add("light-mode");
    }
    })();      
    document.addEventListener("DOMContentLoaded", function() {
        document.documentElement.classList.add("loaded");
    });
</script>
<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
    body {
        font-family: 'Poppins', sans-serif;
    }
    .filter-dropdown {
        position: absolute;
        top: 85px;
        right: 1.5rem;
    }
    .filter-dropdown .dropdown-menu {
        right: 0;
        left: auto;
    }
    .modal-table th,
    .modal-table td {
        border-right: 1px solid #dee2e6; /* Apply vertical border between th and td */
    }
    .modal-table th:last-child,
    .modal-table td:last-child {
        border-right: none; /* Remove border for the last column */
    }
    .small-image {
        max-width: 80px; /* Define the maximum width for the image */
        height: auto; /* Maintain aspect ratio */
    }
</style>
{% endblock %}
{% block content %}
{% include './includes/header.html' %}
{% include "art/arrow_button.html" %}
    <div class="app-content pt-3 p-md-3 p-lg-4">
        <div class="button-container">
            <i class="fa-solid fa-arrow-left" style="cursor:pointer; font-size:1.4rem; margin-right:10px" onclick="goBack()"></i>
            <i class="fa-solid fa-arrow-right" style="cursor:pointer; font-size:1.4rem; margin-right:15px" onclick="goForward()"></i>
        </div>
        <br>
        <div class="container-fluid_list poppins-regular-products">
            <h1 class="app-page-title" id="pageTitle">View All Artworks</h1>
            <div class="filter-dropdown">
                <div class="dropdown-toggle" style="cursor:pointer;" id="filterDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa-solid fa-filter"></i> <span id="selectedFilter">All Artworks</span>
                </div>
                <div class="dropdown-menu" aria-labelledby="filterDropdown">
                    <a class="dropdown-item filter-option" data-filter="All Artworks" href="?filter=all">All Artworks</a>
                    <a class="dropdown-item filter-option" data-filter="Discount" href="?filter=discount">Discount</a>
                    <a class="dropdown-item filter-option" data-filter="Auction" href="?filter=auction">Auction</a>
                </div>
            </div>
            <div class="row poppins-regular-products">
                {% for product in object_list %}
                <div class="artwork-card_list col-6 col-md-4 col-xxl-2">
                    <div class="app-card app-card-doc shadow-sm h-100">
                        <div class="app-card-thumb-holder p-3">
                            <div class="app-card-thumb">
                                <img class="thumb-image" src="{{ MEDIA_URL }}{{ product.product_image }}" alt="">
                            </div>
                        </div>
                        <div class="app-card-body p-3 has-card-actions">
                            <h4 class="app-doc-title truncate mb-0">
                                <a href="#" data-toggle="modal" data-target="#productModal{{ product.id }}">{{ product.product_name }}</a>
                            </h4>                            
                            <div class="app-doc-meta">
                                <div class="btn-group d-flex mx-auto mb-2 mt-2" role="group" aria-label="Basic outlined example">
                                    <a href="{% url 'dashboard:product_update' pk=product.pk %}" type="button" class="btn btn-update btn-sm">Update</a>
                                </div>
                                <div class="btn-group d-flex mx-auto mb-2 mt-2" role="group" aria-label="Basic outlined example">
                                <a href="{% url 'dashboard:product_delete' pk=product.pk %}" type="button" class="btn btn-delete btn-sm">Delete</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Modal -->
                <div class="modal fade" id="productModal{{ product.id }}" tabindex="-1" role="dialog" aria-labelledby="productModalLabel{{ product.id }}" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="productModalLabel{{ product.id }}">{{ product.product_name }}</h5>
                                {% if product.ordermodel_set.exists %} <!-- Check if there are any orders for the product -->
                                    <img src="{% static 'images/assets/sold.png' %}" class="small-image" alt="Sold Image">
                                {% endif %}
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                <style>
                                    
                                </style>
                                <table class="table modal-table">
                                    <tbody>
                                        <tr>
                                            <th scope="row">Product Image</th>
                                            <td><img src="{{ product.product_image.url }}" class="img-fluid" alt="{{ product.product_name }}"></td>
                                        </tr>
                                        <tr>
                                            <th scope="row">Dimensions</th>
                                            <td>
                                                {% if product.length_in_centimeters and product.width_in_centimeters %}
                                                    {{ product.length_in_centimeters }} x {{ product.width_in_centimeters }} cm
                                                {% elif product.foot and product.inches %}
                                                    {{ product.foot }} x {{ product.inches }} ft
                                                {% else %}
                                                    Not specified
                                                {% endif %}
                                            </td>
                                        </tr>
                                        {% if product.sale_type == 'discount' %}
                                        <tr>
                                            <th>Actual Price</th>
                                            <td>₹ {{ product.product_price }}</td>
                                        </tr>
                                        <tr>
                                            <th>Discounted Price</th>
                                            <td>₹ {{ product.get_discounted_price|floatformat:0 }} </td>
                                        </tr>
                                        {% elif product.sale_type == 'auction' %}
                                        <tr>
                                            <th scope="row">Catalogue</th>
                                            <td>{{ product.product_cat }}</td>
                                        </tr>
                                        {% comment %} <tr>
                                            <th scope="row">Order By</th>
                                            <td>{{ product.user }}</td>
                                        </tr> {% endcomment %}
                                        <tr>
                                            <th scope="row">Opening Bid</th>
                                            <td>₹ {{ product.opening_bid }}</td>
                                        </tr>
                                        <tr>
                                        <th scope="row">Last Bid</th>
                                        {% if product.get_total_bids > 0 %}
                                        <td id="last-bid-{{ product.id }}">₹ {{ product.get_last_bid }}</td>
                                        {% else %}
                                            <td>No bids yet</td>
                                        {% endif %}
                                        </tr>
                                        <tr>
                                            <th scope="row">Total Bids</th>
                                            <td id="total-bids-{{ product.id }}">{{ product.get_total_bids }}</td>
                                        </tr>
                                        {% endif %}
                                    </tbody>
                                </table>
                            </div>                            
                            <div class="modal-footer">
                                <button type="button" class="btn btn-primary_details" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>

                {% empty %}
                <h3 class="open-sans-empty dark-mode-heading">No artworks to show</h3>
                {% endfor %}
            </div>
    </div>
    </div>
    {% include './includes/footer.html' %}
<button onclick="topFunction()" id="back-to-top-btn" title="Go to top"><i class="fa-solid fa-angles-up"></i></button>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
<script>
    document.addEventListener('DOMContentLoaded', () => {
        const productId = {{ product.id }};
        const socket = new WebSocket(`ws://${window.location.host}/ws/bid/${productId}/`);
    
        socket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            document.getElementById(`last-bid-${productId}`).innerText = `₹ ${data.bid}`;
            document.getElementById(`total-bids-${productId}`).innerText = parseInt(document.getElementById(`total-bids-${productId}`).innerText) + 1;
        };
    
        document.getElementById('bid-button').addEventListener('click', () => {
            const bid = document.getElementById('bid-input').value;
            socket.send(JSON.stringify({'bid': bid}));
        });
    });
    // Ensure the modal works properly
    document.querySelectorAll('.modal').forEach(modal => {
        modal.addEventListener('shown.bs.modal', () => {
            // Trigger modal-related actions here if needed
        });
    });
</script>
<script src="{% static 'js/artwork_list.js' %}"></script>
{% endblock %}

art_auction/templates/dashboard/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="{% static 'images/assets/ARTIV ICON.png' %}" type="image/x-icon">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'dashboard/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'dashboard/css/form.css' %}">
    <title>{% block title %}{% endblock %}</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    {% block links %}{% endblock %}



</head>
<style>
    body {
        background-color: #f4ede4 !important; /* Soft white gray */
        color: #2B2D42; /* Deep charcoal gray */
    }
    body.dark-mode {
      background-color: #161A1D !important; /* Deep charcoal black */
      color: #E8E8E8; /* Soft white */
    }
</style>

<body class="app">
    {% if user.is_authenticated %}
    <div class="loader"></div>
    {% block content %}{% endblock %}
  
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    {% block js %}{% endblock %}
    <script>
        $(document).ready(function() {
            $('.loader').fadeOut();
        });
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/js/all.min.js" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
   



    {% else %} {% include './404.html' %} {% endif %}
</body>

</html>